service: tz-2021-09
runtime: python39

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always
# access the static resources in the root director
- url: /(.*)
  static_files: \1
  upload: (.*)
  secure: always

# cp app.yaml __sapper__/export
# gcloud app deploy --project tz-nantes --version dummy .