version: 2.1

orbs:
  node: circleci/node@3.0.0
  s3: circleci/aws-s3@2.0.0

jobs:
  build:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn export
      - store_artifacts:
          path: __sapper__/export
      - persist_to_workspace:
          root: ./
          paths:
            - __sapper__/export

  deploy_prod:
    docker:
      - image: cimg/python:3.9
    environment:
      AWS_REGION: eu-west-3 # required by s3 orb even though Cellar does not need it
    steps:
      - attach_workspace:
          at: ./
      - s3/sync:
          from: __sapper__/export
          to: s3://tz.zenika.com
          arguments: |
            --acl public-read \
            --endpoint-url https://cellar-c2.services.clever-cloud.com
          aws-access-key-id: CLEVER_CLOUD_CELLAR_KEY_ID_PROD
          aws-secret-access-key: CLEVER_CLOUD_CELLAR_KEY_SECRET_PROD
      
workflows:
  build_and_deploy_master:
    jobs:
      - build
      - deploy_prod:
          requires: [build]
          filters:
            branches:
              only: master
